FROM node:20.13.1-slim AS builder

# Set working directory
WORKDIR /usr/src/app

# Copy Files
COPY . .
RUN yarn install && yarn build

# Use nginx
FROM nginx:latest

# Build app
COPY --from=builder /usr/src/app/dist/client/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80
